// lib/constants/mock_data.dart
class MockData {
  static final List<Map<String, dynamic>> categories = [
    {'id': '1', 'name': 'Movies', 'icon': 'film'},
    {'id': '2', 'name': 'Concerts', 'icon': 'music'},
    {'id': '3', 'name': 'Comedy', 'icon': 'microphone'},
    {'id': '4', 'name': 'Sports', 'icon': 'volleyball'},
    {'id': '5', 'name': 'Festivals', 'icon': 'star'},
    {'id': '6', 'name': 'Nightlife', 'icon': 'moon'},
  ];

  static final List<Map<String, dynamic>> events = [
    // Concerts
    {
      'id': 'e1',
      'title': 'Arijit Singh Live',
      'subtitle': 'The Symphony Tour',
      'date': '24 Nov 2024',
      'time': '7:00 PM',
      'venue': 'Jio World Garden',
      'location': 'Mumbai',
      'price': 1499.00,
      'rating': 4.8,
      'reviews': '12.5K',
      'image': 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=1000&auto=format&fit=crop',
      'category': 'Concerts',
      'organizer': 'LiveNation',
      'description': 'Get ready for a soulful evening with Arijit Singh as he takes you on a musical journey of emotions and melodies.',
      'isTrending': true,
      'isHero': false,
    },
    {
      'id': 'e2',
      'title': 'Coldplay',
      'subtitle': 'Music of the Spheres',
      'date': '18 Jan 2025',
      'time': '7:00 PM',
      'venue': 'DY Patil Stadium',
      'location': 'Mumbai',
      'price': 4999.00,
      'rating': 4.9,
      'reviews': '50K',
      'image': 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?q=80&w=1000&auto=format&fit=crop',
      'category': 'Concerts',
      'organizer': 'BookMyShow',
      'description': 'Experience the ultimate music festival with Coldplay featuring stunning visuals and state-of-the-art sound systems.',
      'isTrending': true,
      'isHero': true,
    },
    {
      'id': 'e3',
      'title': 'Ed Sheeran',
      'subtitle': 'Mathematics Tour',
      'date': '10 Feb 2025',
      'time': '8:00 PM',
      'venue': 'Bandra Kurla Complex',
      'location': 'Mumbai',
      'price': 3500.00,
      'rating': 4.7,
      'reviews': '34K',
      'image': 'https://images.unsplash.com/photo-1470229722913-7c092bb49ab4?q=80&w=1000&auto=format&fit=crop',
      'category': 'Concerts',
      'organizer': 'AEG Presents',
      'description': 'Catch Ed Sheeran live performing hits from his latest albums along with all-time classics.',
      'isTrending': false,
      'isHero': false,
    },
    // Comedy
    {
      'id': 'e4',
      'title': 'Zakir Khan',
      'subtitle': 'Tathastu Live',
      'date': '05 Dec 2024',
      'time': '8:00 PM',
      'venue': 'NCPA',
      'location': 'Mumbai',
      'price': 999.00,
      'rating': 4.9,
      'reviews': '22K',
      'image': 'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?q=80&w=1000&auto=format&fit=crop',
      'category': 'Comedy',
      'organizer': 'OML',
      'description': 'Join the Sakht Launda for an evening of relatable humor and incredible storytelling.',
      'isTrending': true,
      'isHero': false,
    },
    {
      'id': 'e5',
      'title': 'Vir Das',
      'subtitle': 'Mind Fool Tour',
      'date': '12 Dec 2024',
      'time': '7:30 PM',
      'venue': 'Bal Gandharva Rang Mandir',
      'location': 'Pune',
      'price': 1499.00,
      'rating': 4.8,
      'reviews': '15K',
      'image': 'https://images.unsplash.com/photo-1527224857830-43a7ebb8545e?q=80&w=1000&auto=format&fit=crop',
      'category': 'Comedy',
      'organizer': 'Vir Das Comedy',
      'description': 'International Emmy winner Vir Das brings his highly acclaimed Mind Fool tour to Pune.',
      'isTrending': false,
      'isHero': false,
    },
    // Sports
    {
      'id': 'e6',
      'title': 'India vs Australia',
      'subtitle': 'Border-Gavaskar Trophy',
      'date': '22 Nov 2024',
      'time': '9:30 AM',
      'venue': 'Wankhede Stadium',
      'location': 'Mumbai',
      'price': 1200.00,
      'rating': 4.7,
      'reviews': '30K',
      'image': 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?q=80&w=1000&auto=format&fit=crop',
      'category': 'Sports',
      'organizer': 'BCCI',
      'description': 'Witness the thrilling cricket match between India and Australia at the iconic Wankhede Stadium.',
      'isTrending': true,
      'isHero': false,
    },
    {
      'id': 'e7',
      'title': 'Mumbai City FC vs Mohun Bagan',
      'subtitle': 'ISL Final',
      'date': '02 Dec 2024',
      'time': '7:30 PM',
      'venue': 'Mumbai Football Arena',
      'location': 'Mumbai',
      'price': 500.00,
      'rating': 4.6,
      'reviews': '8K',
      'image': 'https://images.unsplash.com/photo-1518605368461-1ee116035f49?q=80&w=1000&auto=format&fit=crop',
      'category': 'Sports',
      'organizer': 'ISL',
      'description': 'The biggest clash in Indian football. Do not miss the ISL Final.',
      'isTrending': true,
      'isHero': true,
    },
    // Festivals
    {
      'id': 'e8',
      'title': 'Lollapalooza India',
      'subtitle': 'Music & Arts Festival',
      'date': '27 Jan 2025',
      'time': '1:00 PM',
      'venue': 'Mahalaxmi Race Course',
      'location': 'Mumbai',
      'price': 5999.00,
      'rating': 4.8,
      'reviews': '40K',
      'image': 'https://images.unsplash.com/photo-1533174000220-db9d1bd3db34?q=80&w=1000&auto=format&fit=crop',
      'category': 'Festivals',
      'organizer': 'BookMyShow Live',
      'description': 'Lollapalooza returns to India with a stellar lineup of global and local artists.',
      'isTrending': true,
      'isHero': false,
    },
    {
      'id': 'e9',
      'title': 'Sunburn Goa',
      'subtitle': 'EDM Festival',
      'date': '28 Dec 2024',
      'time': '2:00 PM',
      'venue': 'Vagator Beach',
      'location': 'Goa',
      'price': 3999.00,
      'rating': 4.9,
      'reviews': '60K',
      'image': 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=1000&auto=format&fit=crop',
      'category': 'Festivals',
      'organizer': 'Percept Live',
      'description': 'The ultimate year-end party in Goa with the biggest DJs in the world.',
      'isTrending': true,
      'isHero': false,
    },
    // Nightlife
    {
      'id': 'e10',
      'title': 'Boiler Room',
      'subtitle': 'Mumbai Edition',
      'date': '15 Nov 2024',
      'time': '9:00 PM',
      'venue': 'Secret Location',
      'location': 'Mumbai',
      'price': 2500.00,
      'rating': 4.8,
      'reviews': '12K',
      'image': 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=1000&auto=format&fit=crop',
      'category': 'Nightlife',
      'organizer': 'Boiler Room',
      'description': 'An underground techno experience featuring top international and local selectors.',
      'isTrending': true,
      'isHero': false,
    },
    {
      'id': 'e11',
      'title': 'Neon Nights',
      'subtitle': 'Techno Party',
      'date': '20 Nov 2024',
      'time': '10:00 PM',
      'venue': 'Kitty Su',
      'location': 'Mumbai',
      'price': 1500.00,
      'rating': 4.5,
      'reviews': '5K',
      'image': 'https://images.unsplash.com/photo-1542204165-65bf26472b9b?q=80&w=1000&auto=format&fit=crop',
      'category': 'Nightlife',
      'organizer': 'Kitty Su',
      'description': 'Dance the night away with pulsating techno beats and glowing neon aesthetics.',
      'isTrending': false,
      'isHero': false,
    },
    // Theatre
    {
      'id': 'e12',
      'title': 'Mughal-e-Azam',
      'subtitle': 'The Musical',
      'date': '05 Jan 2025',
      'time': '6:30 PM',
      'venue': 'Nita Mukesh Ambani Cultural Centre',
      'location': 'Mumbai',
      'price': 2500.00,
      'rating': 4.9,
      'reviews': '25K',
      'image': 'https://images.unsplash.com/photo-1507676184212-d0330a15233c?q=80&w=1000&auto=format&fit=crop',
      'category': 'Theatre',
      'organizer': 'Shapoorji Pallonji',
      'description': 'Experience the epic romance brought to life on stage with breathtaking costumes and live singing.',
      'isTrending': false,
      'isHero': true,
    },
    {
      'id': 'e13',
      'title': 'Hamilton',
      'subtitle': 'International Tour',
      'date': '12 Mar 2025',
      'time': '7:00 PM',
      'venue': 'NCPA',
      'location': 'Mumbai',
      'price': 4500.00,
      'rating': 5.0,
      'reviews': '100K',
      'image': 'https://images.unsplash.com/photo-1460723237483-7a6dc9d0b212?q=80&w=1000&auto=format&fit=crop',
      'category': 'Theatre',
      'organizer': 'Broadway Asia',
      'description': 'The multi-award-winning musical masterpiece finally arrives in India.',
      'isTrending': true,
      'isHero': false,
    },
    // Workshops & Tech
    {
      'id': 'e14',
      'title': 'AI Summit 2024',
      'subtitle': 'Future of Tech',
      'date': '10 Dec 2024',
      'time': '9:00 AM',
      'venue': 'Jio World Convention Centre',
      'location': 'Mumbai',
      'price': 5000.00,
      'rating': 4.7,
      'reviews': '3K',
      'image': 'https://images.unsplash.com/photo-1531482615713-2afd69097998?q=80&w=1000&auto=format&fit=crop',
      'category': 'Tech Events',
      'organizer': 'TechCrunch',
      'description': 'Join industry leaders to discuss the impact of AI on the future of humanity and business.',
      'isTrending': false,
      'isHero': false,
    },
    {
      'id': 'e15',
      'title': 'Pottery Masterclass',
      'subtitle': 'With Aditi Studio',
      'date': '18 Nov 2024',
      'time': '3:00 PM',
      'venue': 'Bandra West',
      'location': 'Mumbai',
      'price': 1200.00,
      'rating': 4.9,
      'reviews': '500',
      'image': 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?q=80&w=1000&auto=format&fit=crop',
      'category': 'Workshops',
      'organizer': 'Aditi Studio',
      'description': 'A hands-on workshop to learn the art of wheel throwing and ceramic design.',
      'isTrending': false,
      'isHero': false,
    },
    // Food Experiences
    {
      'id': 'e16',
      'title': 'The Secret Supper Club',
      'subtitle': '7-Course Tasting Menu',
      'date': '25 Nov 2024',
      'time': '8:30 PM',
      'venue': 'Colaba',
      'location': 'Mumbai',
      'price': 4000.00,
      'rating': 4.8,
      'reviews': '1.2K',
      'image': 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=1000&auto=format&fit=crop',
      'category': 'Food Experiences',
      'organizer': 'Chef Vikas',
      'description': 'An exclusive, invite-only dining experience focusing on modern Indian gastronomy.',
      'isTrending': false,
      'isHero': false,
    },
    {
      'id': 'e17',
      'title': 'Gin Tasting Masterclass',
      'subtitle': 'Botanical Journeys',
      'date': '02 Dec 2024',
      'time': '7:00 PM',
      'venue': 'The Botanist',
      'location': 'Mumbai',
      'price': 2500.00,
      'rating': 4.7,
      'reviews': '800',
      'image': 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=1000&auto=format&fit=crop',
      'category': 'Food Experiences',
      'organizer': 'Diageo',
      'description': 'Explore the nuances of craft gins paired with artisanal tonics and garnishes.',
      'isTrending': false,
      'isHero': false,
    },
    // Art Exhibitions
    {
      'id': 'e18',
      'title': 'Van Gogh 360',
      'subtitle': 'Immersive Art Experience',
      'date': 'Ongoing',
      'time': '10:00 AM',
      'venue': 'World Trade Centre',
      'location': 'Mumbai',
      'price': 999.00,
      'rating': 4.6,
      'reviews': '18K',
      'image': 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?q=80&w=1000&auto=format&fit=crop',
      'category': 'Art Exhibitions',
      'organizer': 'Immersive Art Co',
      'description': 'Step into the paintings of Vincent Van Gogh in this mesmerizing 360-degree projection mapping exhibit.',
      'isTrending': true,
      'isHero': false,
    },
    {
      'id': 'e19',
      'title': 'Kala Ghoda Arts Festival',
      'subtitle': 'Cultural Celebration',
      'date': '01 Feb 2025',
      'time': '10:00 AM',
      'venue': 'Kala Ghoda District',
      'location': 'Mumbai',
      'price': 0.00,
      'rating': 4.9,
      'reviews': '50K',
      'image': 'https://images.unsplash.com/photo-1544531586-fde5298cdd40?q=80&w=1000&auto=format&fit=crop',
      'category': 'Festivals',
      'organizer': 'KGAF Assoc',
      'description': 'Asia\'s largest multi-cultural street festival featuring art installations, workshops, and performances.',
      'isTrending': true,
      'isHero': false,
    }
  ];

  static final List<Map<String, dynamic>> userBookings = [
    {
      'id': 'BMS2411240915',
      'event': events[0], // Arijit Singh
      'ticketCount': 2,
      'totalPrice': 2998.00,
      'status': 'Upcoming',
      'bookingDate': 'Oct 01, 2024',
      'qrCode': 'mock-qr-code-data',
    },
    {
      'id': 'BMS2501180916',
      'event': events[1], // Coldplay
      'ticketCount': 3,
      'totalPrice': 14997.00,
      'status': 'Upcoming',
      'bookingDate': 'Oct 05, 2024',
      'qrCode': 'mock-qr-code-data',
    },
    {
      'id': 'BMS2411220917',
      'event': events[5], // India vs Aus
      'ticketCount': 2,
      'totalPrice': 2400.00,
      'status': 'Past',
      'bookingDate': 'Sep 20, 2024',
      'qrCode': 'mock-qr-code-data-2',
    }
  ];
}
